In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score,roc_curve, auc 
import sklearn.metrics as sm

from sklearn import metrics

In [8]:
dataset = pd.read_csv('output_test.csv')
X= dataset.drop(['label'], axis=1)   # 取出用于建模的特征列X
Y = dataset['label']   # 取出标签列Y

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=420)

In [9]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
classifier = SVC(kernel='linear',class_weight="balanced", random_state = 420, probability=True)

In [11]:
classifier.fit(X_train, Y_train)

y_pred = classifier.predict(X_test)
cp = sm.classification_report(Y_test, y_pred)
print("---------------分类报告\n", cp)

---------------分类报告
               precision    recall  f1-score   support

           0       0.55      0.31      0.40       149
           1       0.22      0.41      0.29        51
           2       0.29      0.30      0.29        84
           3       0.42      0.53      0.47        76

    accuracy                           0.37       360
   macro avg       0.37      0.39      0.36       360
weighted avg       0.42      0.37      0.37       360



In [12]:

print('Accuracy score:', accuracy_score(Y_test, y_pred))
print('Recall:', recall_score(Y_test, y_pred, average='weighted'))
print('F1-score:', f1_score(Y_test, y_pred, average='weighted'))
print('Precision score:', precision_score(Y_test, y_pred, average='weighted'))
# y_test_proba_rfc =classifier.predict_proba(X_test)
# false_positive_rate_rfc, recall_rfc, thresholds_rfc = roc_curve(Y_test, y_test_proba_rfc[:, 1])  
# roc_auc_rfc = auc(false_positive_rate_rfc, recall_rfc)   
# print(roc_auc_rfc )

Accuracy score: 0.36666666666666664
Recall: 0.36666666666666664
F1-score: 0.37187333010442086
Precision score: 0.4166386902722809


In [7]:
param_grid=[{
            'gamma':[10, 5, 2.5, 1.5, 1.25, 0.625, 0.3125, 0.15, 0.05, 0.025, 0.0125],             
            },
           ]

In [8]:
classifier1 = SVC(kernel='rbf',class_weight="balanced", random_state = 420, probability=True)
grid_search = GridSearchCV(classifier1, param_grid, n_jobs = -1, verbose = 1, cv=10)     
grid_search.fit(X_train, Y_train)   
classifier1 = grid_search.best_estimator_ 
grid_search.best_score_ 

Fitting 10 folds for each of 11 candidates, totalling 110 fits


0.8392857142857144

In [9]:
grid_search.best_params_ 

{'gamma': 0.05}

In [10]:

y_pred1 = classifier1.predict(X_test)
cp = sm.classification_report(Y_test, y_pred1)
print("---------------分类报告\n", cp)
cm = confusion_matrix(Y_test, y_pred1)
print(cm)
print('Accuracy score:', accuracy_score(Y_test, y_pred1))
print('Recall:', recall_score(Y_test, y_pred1, average='weighted'))
print('F1-score:', f1_score(Y_test, y_pred1, average='weighted'))
print('Precision score:', precision_score(Y_test, y_pred1, average='weighted'))
# y_test_proba_rfc =classifier1.predict_proba(X_test)
# false_positive_rate_rfc, recall_rfc, thresholds_rfc = roc_curve(Y_test, y_test_proba_rfc[:, 1])  
# roc_auc_rfc = auc(false_positive_rate_rfc, recall_rfc)   
# print(roc_auc_rfc )

---------------分类报告
               precision    recall  f1-score   support

           0       0.89      0.83      0.86       149
           1       0.69      0.88      0.78        51
           2       0.79      0.82      0.81        84
           3       0.80      0.72      0.76        76

    accuracy                           0.81       360
   macro avg       0.79      0.81      0.80       360
weighted avg       0.82      0.81      0.81       360

[[124   8  10   7]
 [  4  45   2   0]
 [  1   7  69   7]
 [ 10   5   6  55]]
Accuracy score: 0.8138888888888889
Recall: 0.8138888888888889
F1-score: 0.8147754643633348
Precision score: 0.8206359872698467


In [11]:
param_grid=[{
            'gamma':[1,2,3,4,5,6,7,8,9,10],  
            'C':[0.0001,0.001,0.01,0.1,1,10,100,1000,10000], 
            },
           ]

In [12]:
classifier2 = SVC(kernel='sigmoid',class_weight="balanced", random_state = 420, probability=True)
grid_search = GridSearchCV(classifier2, param_grid, n_jobs = -1, verbose = 1, cv=10)     
grid_search.fit(X_train, Y_train)   
classifier2 = grid_search.best_estimator_ 
grid_search.best_score_ 

Fitting 10 folds for each of 90 candidates, totalling 900 fits


0.6095238095238095

In [13]:

y_pred2 = classifier2.predict(X_test)
cp = sm.classification_report(Y_test, y_pred2)
print("---------------分类报告\n", cp)
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score
print('Accuracy score:', accuracy_score(Y_test, y_pred2))
print('Recall:', recall_score(Y_test, y_pred2, average='weighted'))
print('F1-score:', f1_score(Y_test, y_pred2, average='weighted'))
print('Precision score:', precision_score(Y_test, y_pred2, average='weighted'))

---------------分类报告
               precision    recall  f1-score   support

           0       0.94      0.42      0.58       149
           1       0.45      0.67      0.54        51
           2       0.67      0.56      0.61        84
           3       0.47      0.92      0.62        76

    accuracy                           0.59       360
   macro avg       0.63      0.64      0.59       360
weighted avg       0.71      0.59      0.59       360

Accuracy score: 0.5916666666666667
Recall: 0.5916666666666667
F1-score: 0.5889453039065442
Precision score: 0.7088733193229838


13

In [7]:
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[32  9]
 [17 17]]


In [17]:
empty = np.array([[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0]])
n=1
while n < 51:
    
    
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state =n)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    classifier = SVC(kernel='linear',class_weight="balanced", random_state = 420, probability=True)
    classifier.fit(X_train, Y_train)
    
    y_pred = classifier.predict(X_test)   
    y_updatapred = classifier.predict(X_train)
    from sklearn.metrics import confusion_matrix, roc_auc_score
    cm = confusion_matrix(Y_test, y_pred)   
    cm_updata = confusion_matrix(Y_train, y_updatapred)
    auc = roc_auc_score(Y_test, y_pred,multi_class='ovo')
    auc_updata = roc_auc_score(Y_train, y_updatapred)
    a = cm[0,0]
    b = cm[0,1]
    c = cm[1,0]
    d = cm[1,1]
    sen = d/(d+c)
    sep = a/(a+b)
    acc = (a+d)/(a+b+c+d)
    pre = a/(a+c)
    F1 = (2*a)/(2*a+c+b)
    
    a_updata = cm_updata[0,0]
    b_updata = cm_updata[0,1]
    c_updata = cm_updata[1,0]
    d_updata = cm_updata[1,1]
    
    sen_updata = d_updata/(d_updata + c_updata)
    sep_updata = a_updata/(a_updata + b_updata)
    
    acc_updata = (a_updata+d_updata)/(a_updata+b_updata+c_updata+d_updata)
    pre_updata = a_updata/(a_updata + c_updata)
    F1_updata = (2*a_updata)/(2*a_updata+c_updata+b_updata)
    
    first = np.array([[n],[sen],[sep],[acc],[pre],[F1],[auc],[sen_updata],[sep_updata],[acc_updata],[pre_updata],[F1_updata],[auc_updata]])
    second = np.hstack((empty,first))
    empty = second
    n = n + 1
    print(n)
final_par = np.delete(second,0,axis=1)
print (final_par)
final_parT = final_par.T
np.savetxt('SVC_dr',final_parT,delimiter=',')

ValueError: multi_class must be in ('ovo', 'ovr')